# Generated by Django 2.0.4 on 2018-04-22 12:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_number', models.IntegerField()),
                ('batiment', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Temperature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temp', models.IntegerField()),
                ('date', models.DateTimeField(verbose_name='date published')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='collecte.Room')),
            ],
        ),
    ]
